import 'react-perfect-scrollbar/dist/css/styles.css';
import "../styles/index.css";

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import classnames from 'classnames';
import { ThemeProviders } from '@/components/theme-providers';
import { NextAuthProvider } from "./SessionProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PDF Chatbot',
  description: 'Generated by Giulio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classnames("dark:bg-black", inter.className) }>
        <ThemeProviders>
          <NextAuthProvider>
          {children}
          </NextAuthProvider>
        </ThemeProviders>
      </body>
    </html>
  )
}
